# Generated by Django 5.1.6 on 2025-02-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=30, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('price', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('volume_24h', models.BigIntegerField(default=0)),
                ('circulating_supply', models.BigIntegerField(default=0)),
                ('total_supply', models.BigIntegerField(blank=True, default=None, null=True)),
                ('max_supply', models.BigIntegerField(blank=True, default=None, null=True)),
                ('change_24h', models.FloatField(default=0.0)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
